# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/" =
    {
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=25%" "mode=755" ];
    };

  #  fileSystems."/home/hil" = 
  #    { device = "none";
  #      fsType = "tmpfs";
  #      options = [ "defaults" "size=25%" "mode=755" ];
  #    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/3c978b83-6f9f-42e0-a4d0-846ece912130";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:1" ];
    };

  fileSystems."/persistent" =
    {
      device = "/dev/disk/by-uuid/3c978b83-6f9f-42e0-a4d0-846ece912130";
      fsType = "btrfs";
      options = [ "subvol=@persistent" "noatime" "compress=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/.snapshots" =
    {
      device = "/dev/disk/by-uuid/3c978b83-6f9f-42e0-a4d0-846ece912130";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "noatime" "compress=zstd:1" ];
    };

  fileSystems."/tmp" =
    {
      device = "/dev/disk/by-uuid/3c978b83-6f9f-42e0-a4d0-846ece912130";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "noatime" "compress=zstd:1" ];
    };

  fileSystems."/swap" =
    {
      device = "/dev/disk/by-uuid/3c978b83-6f9f-42e0-a4d0-846ece912130";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/620C-17EE";
      fsType = "vfat";
    };

  fileSystems."/extend" =
    {
      device = "/dev/disk/by-uuid/6e0c07ce-2755-440c-a442-5364a3f162d0";
      fsType = "btrfs";
      options = [ "subvol=@data" "noatime" "compress=zstd:1" ];
    };

  swapDevices = [{ device = "/swap/swapfile"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = [
      pkgs.rocmPackages.clr.icd
      pkgs.amdvlk
    ];
  };
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;

    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      # Make sure to use the correct Bus ID values for your system!
      nvidiaBusId = "PCI:1:0:0";
      amdgpuBusId = "PCI:6:0:0";
    };
  };
}
